name: 🚀 Create Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'New version (e.g. 0.1.4)'
        required: true
      release_message:
        description: 'Release message'
        required: false

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.inputs.version }}
      TAG: v${{ github.event.inputs.version }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: true
      
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with:
          # Install a specific version of uv.
          version: "0.8.6"

      - name: Bump version
        run: |
          uv version ${VERSION}

      - name: Commit bump
        run: |
          git config user.name  "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add pyproject.toml
          git commit -m "release: bump version to ${VERSION}"
          git push origin HEAD:${{ github.ref }}
          
      - name: Create release
        env:
          GITHUB_TOKEN: ${{ secrets.RELEASE_PAT }}
        run: |
          printf '%b' "${{ github.event.inputs.release_message }}" > release-notes.md
          gh release create "${TAG}" \
              --repo="$GITHUB_REPOSITORY" \
              --title="${GITHUB_REPOSITORY#*/} ${TAG}" \
              --generate-notes \
              --notes-file=release-notes.md \
              --fail-on-no-commits